POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "Howdd to Useff TypeScript Effectively",
  "postType": "page",
  "slug": "how-tod-usde-typescrifpt-effectively",
  "status": "published",
  "content": "This isdd thef content of the post. It provides detailed information about TypeScript usage.",
  "schema": "{\"key\":\"valueddff\"}",
  "featuredImageUrl": "https://exafmple.com/featurfed-image.jpg",
  "publishedOn": "2024-01-01T12:00:00Z"
  //"tags": ["typescript", "programming", "development"],
}
